### ISSUE TITLE
Cant hide levels?

### ISSUE THREAD

**Issue by prasadienator** [ErikFrits/EF-Tools#15]
getting following error.
Using it for the first time. Is there some step i missed?
﻿

Traceback (most recent call last): 
 File "C:\Users\prasadi\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Maintenance.panel\Warnings.pulldown\Isolate Warnings.pushbutton\script.py", line 257, in do_stuff 
 view.SetCategoryHidden(ElementId(BuiltInCategory.OST_Levels), True) # Hide Levels 
Exception: Category cannot be hidden. 
Parameter name: categoryId

**Comment by ErikFrits** [comment]
🙏Thanks for submitting the bug.

👀 I looked at the code and it looks like the error happens if you have default ViewTemplate assigned to one of the 3D View Types. I managed to get the same error by using this logic.

✅ I fixed the bug. Now it will make sure to remove any ViewTemplates from a newly created 3D view that is used for warnings.

💽 You can reinstall EF-Tools and try it again.
(Go to pyRevit extensions menu and Remove/Install new)

🤷‍♂️ Sorry for inconveniences.
