### ISSUE TITLE
'module' object has no attribute 'engine'

### ISSUE THREAD

**Issue by TZwielehner** [ErikFrits/EF-Tools#8]
I get this error when I run e.g. the "Shorten Ribbon names" command. Any ideas?

`IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\...\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\UI.panel\col1.stack\ShortenRibbonNames.pushbutton\script.py", line 43, in <module>
 File "C:\Users\...\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\__init__.py", line 74, in <module>
AttributeError: 'module' object has no attribute 'engine'`

**Comment by ErikFrits** [comment]
Hi sorry, I have found the email about this issue in my spam...
From what I see, the issue does not come from EF-Tools directly.

@TZwielehner 

Do you use Revit 2023? 
I think I saw similar issue reported by pyRevit users once they installed it to Revit 2023, and I believe it was resolved. Try updating your pyRevit to the latest version.


Let me know if it resolved your issue.

**Comment by TZwielehner** [comment]
Hi Erik,

That's fine, thanks for reaching out. I'll give it another try.

Btw, my colleague Oliver visited you and Jakob Steiner at RLP two weeks
ago, so maybe we have a way to collaborate some time?

Also, if you want to check out "my tools", you can find them here:
https://apps.autodesk.com/en/Publisher/PublisherHomepage?ID=XFZZNAAU899Y

I also work on a report app for Revit (for everything from nicely formatted
room book, flat documentation, door signs to outlet stickers).

For prototyping I use pyrevit quite frequently, however, not in a such
structured way as you apparently. So, would be great to exchange ideas some
time.

Enjoy your weekend!

Thomas

Erik Frits ***@***.***> schrieb am Fr., 6. Mai 2022, 11:39:

**Comment by ErikFrits** [comment]
Hi Thomas,
Oh yeah, I had a brief interaction with Oliver recently.

I am open for collaborations but I am mostly interested in open-source projects for now. It will heavily depend on my spare time available because my YouTube channel eats a huge chunk of my time right now, but feel free to share your ideas for collaborations, I am open minded!

Yeah, pyRevit is amazing! Sometimes I can get something nice in a very short period of time and I love that I don't need to reopen Revit! 

Nice weekend ;) 
Erik
